---
title: "김상규"
author: "김상규"
date: '2019 6 25 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 모비율 추정 연습문제  
  
## 1번문제  
  
### 학생의 비율 p에 대한 신뢰도 95% 신뢰 구간  
```{r}
print('0.5 - 1.96 * (sqrt(0.5 * 0.5) / n) <= p <= 0.5 + 1.96 * (sqrt(0.5 * 0.5) / n)')
```
  
## 2번문제  
### 100명, 4/5 선호, p에 대한 95% 신뢰구간  
```{r}
ll <- 4/5 - 1.96 * (sqrt((4/5) * (1/5)) / 100)

ul <- 4/5 + 1.96 * (sqrt((4/5) * (1/5)) / 100)

sprintf('%f <= p <= %f', ll, ul)
```
  
## 3번문제  
### 1000명, 430/1000 흡연자, p에 대한 90% 신뢰구간  
```{r}
ll <- 430/1000 - 1.64 * (sqrt((430/1000) * (570/1000)) / 1000)

ul <- 430/1000 + 1.64 * (sqrt((430/1000) * (570/1000)) / 1000)

sprintf('%f <= p <= %f', ll, ul)
```
  
# 1-Sample T 테스트 연습문제  
## 4번문제  
### 샘플이 모집단과 같은가?
```{r}
sampleA <- c(980, 1008, 968, 1032, 1012, 996, 1021, 1002, 996, 1017)
t.test(sampleA, mu = 1000)
# p-value 값이 0.61 이므로 영가설을 채택 = 모집단과 같다.
```
  
## 5번문제
### 평균이 올랐는가?
```{r}
sampleB <- c(58, 49, 39, 99, 32, 88, 62, 30, 55, 65, 44, 55, 57, 53, 88, 42, 39)
t.test(sampleB, mu = 55, alternative = 'greater')
# p-value 값이 0.40 이므로 영가설을 채택 = 평균은 오르지 않았다.\
```
  
  
## 6번문제
### 알코올 섭취량이 달라졌는가?
```{r}
sampleC <- c(15.50, 11.21, 12.67, 8.87, 12.15, 9.88, 2.06, 14.50, 0, 4.97)
t.test(sampleC, mu = 8.1)
# p-value 값이 0.53 이므로 영가설을 채택 = 알코올 섭취량은 달라지지 않았다.
```