---
title: "김상규"
author: "김상규"
date: '2019 6 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 분산분석 및 적합도와 독립성 검정 연습문제
## 1. 3개 호수의 산소량은 같다고 할 수 있는가?
```{r}
a1 <- data.frame(호수 = 1, ppm = c(5, 7, 6, 8, 6, 
                                   7, 8, 8, 6, 10))
a2 <- data.frame(호수 = 2, ppm = c(6, 8, 9, 11 ,13, 
                                   12 ,10, 8, 9, 10))
a3 <- data.frame(호수 = 3, ppm = c(14, 25, 26, 18, 19, 
                                   22, 21, 16, 20, 30))
a <- rbind(a1,a2,a3)
head(a)
ow <- lm(ppm ~ 호수, data = a)
anova(ow)

# p-value(0) <= 0.05 이므로 대립가설을 채택한다. 3개 호수의 산소량은 같지 않다.
```
  
## 2. 3개 채소의 가격은 같다고 할 수 있는가?
```{r}
b1 <- data.frame(채소 = 'A', 가격 = c(15.5, 14.3, 16.3, 13.5, 15.7, 16.4, 14.7))
b2 <- data.frame(채소 = 'B', 가격 = c(14.7, 16.3, 15.5, 15.2, 16.3, 13.5, 15.4))
b3 <- data.frame(채소 = 'C', 가격 = c(15.5, 13.2, 16.5, 15.7, 15.3, 15.2, 14.8))
b <- rbind(b1,b2,b3)
head(b)
ow <- lm(가격 ~ 채소, data = b)
anova(ow)
# p-value(0.98) >= 0.05 이므로 귀무가설을 채택한다. 3개의 채소 가격은 같다.

```
  
## 3. 어느 공정의 부적합품률은 15%로 적합한가?
```{r}
c <- data.frame( 합격 = 64, 불합격 = 16)
rownames(c) <- '빈도'
head(c)
chisq.test(c, p = c(0.85, 0.15))
# p-value(0.21) >= 0.05 이므로 귀무가설을 채택한다. 공정의 부적합품률은 15%이다.
```
  
## 4. 음주량과 흡연량 사이에 연관이 있는가?
```{r}
d <- data.frame('피움' = c(23 + 21 + 31 + 48, 13+23),
                '안피움' = c(63 + 159, 119))
rownames(d) <- c('마심', '못마심')
head(d)
chisq.test(d)
# p-value(0.007) <= 0.05 이므로 대립가설을 채택한다. 음주량과 흡연량 사이에는 연관이 있다.
```
ch
