---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 필요 라이브러리 설치
```{r}
library(lawstat)
library(agricolae)
```
  
## 1번 문제
##### 다음은 3개 호수의 산소량의 차이가 있는지 없는지 알아보기 위하여 
##### 각 호수에서 10곳을 선택하여 수심 1m의 물로부터 산소량(ppm)을 측정한 자료이다.
##### 3개 호수의 산소량이 같다고 할 수 있는가?
```{r}
a1 <- data.frame(group = 1, ppm = c(5, 7, 6, 8, 6, 
                                    7, 8, 8, 6, 10))
a2 <- data.frame(group = 2, ppm = c(6, 8, 9, 11 ,13, 
                                    12 ,10, 8, 9, 10))
a3 <- data.frame(group = 3, ppm = c(14, 25, 26, 18, 19, 
                                    22, 21, 16, 20, 30))
a <- rbind(a1,a2,a3)

a$group <- as.factor(a$group)

shapiro.test(a1$ppm)
shapiro.test(a2$ppm)
shapiro.test(a3$ppm)
# 모두 p-value >= 0.05 에 근사하거나 크므로 귀무가설을 채택한다. 3개 호수의 산소량은 정규성을 가진다고 가정한다.

# lm 모델을 만든다.
a_lm <- lm(ppm ~ group, data = a)

# 각 호수 별 산소량에 대한 분산이 모두 동일한 지 검정한다. 
# 이에 대해서는 Levene의 검정과 Bartlett의 검정 그리고 많이 쓰는 anova 검정이 있다. 
# 모두 세집단 이상의 경우에 대해 등분산성을 검정 시 사용하는 검정법이고 해당 통계량이 특정한 분포에 근사한다는 성질을 이용한다. 
levene.test(a$ppm, a$group)
bartlett.test(a$ppm, a$group)
anova(a_lm)

# 모두 p-value <= 0.05 이므로 대립가설을 채택한다. 3개 호수의 산소량 등분산성을 가지지 않는다.

# 분산이 각 호수의 어느 곳에서 차이가 발생하는지 확인한다.
# TurkeyHSD 방법을 시도한다.
TukeyHSD(aov(a_lm))
# 호수 3과의 비교에서 p-value <= 0.05이므로 호수 3과 1,2는 현저히 차이가 난다.

# Duncan 방법을 시도한다.
a_dunc <- duncan.test(aov(a_lm), 'group', alpha = 0.05, group = T, console = T); a_dunc

# Scheffe 방법을 시도한다.
a_sche <- scheffe.test(aov(a_lm), 'group', alpha = 0.05, group = T, console = T); a_sche


# 두 검정 모두 호수3의 산소량과 나머지 두 집단의 차이가 있다고 결론을 내린다.
# 결과적으로 3가지 다중비교 방법 모두 같은 결론을 제시하고 있다.
```
  
## 2번 문제
##### 다음은 3개 채소에 대한 도매시장 7곳의 가격이다. 3개 채소의 가격이 같다고 할 수 있는가?
```{r}
b1 <- data.frame(채소 = 'A', 가격 = c(15.5, 14.3, 16.3, 13.5, 15.7, 16.4, 14.7))
b2 <- data.frame(채소 = 'B', 가격 = c(14.7, 16.3, 15.5, 15.2, 16.3, 13.5, 15.4))
b3 <- data.frame(채소 = 'C', 가격 = c(15.5, 13.2, 16.5, 15.7, 15.3, 15.2, 14.8))
b <- rbind(b1,b2,b3)
b$채소 <- as.factor(b$채소)
head(b)
b_lm <- lm(가격 ~ 채소, data = b)

shapiro.test(b1$가격)
shapiro.test(b2$가격)
shapiro.test(b3$가격)
# 모두 p-value >= 0.05 이므로 귀무가설을 채택한다. 3개 채소의 가격은 정규성을 가진다고 가정한다.

anova(b_lm)
levene.test(b$가격, b$채소)
bartlett.test(b$가격, b$채소)
# p-value >= 0.05 이므로 귀무가설을 채택한다. 3개의 채소 가격은 같다.
```
  
## 3번 문제
##### 어느 공정의 부적합품률은 15% 이다. 시료 80개를 추출하여 검사한 결과 불량이 16개이다. 
##### 유의수준 5%로 적합도 검정을 하시오.
```{r}
c <- data.frame( 합격 = 64, 불합격 = 16)
rownames(c) <- '빈도'
chisq.test(c, p = c(0.85, 0.15))
# p-value(0.21) >= 0.05 이므로 귀무가설을 채택한다. 공정의 부적합품률은 15%이다.
```
  
## 4번 문제
##### 다음은 음주량과 흡연량 데이터이다. 
##### 이 표로부터 음주량과 흡연량 사이에 연관이 있는지 확인하시오.
```{r}
d <- data.frame('한갑이상' = c(23, 31, 13),
                '한갑이하' = c(21, 48, 23),
                '안피움' = c(63, 159, 119))
rownames(d) <- c('반병 이상', '반병 이하', '못마심')
head(d)
# 카이제곱 검정으로 독립성을 판단한다.
d_chi <- chisq.test(d); d_chi
# p-value(0.01) <= 0.05 이므로 대립가설을 채택한다. 음주량과 흡연량 사이에는 연관이 있다.
addmargins(d_chi$expected)

```
  
  